### ISSUE TITLE
Invalid link in README

### ISSUE THREAD

**Issue by BayuDC** [gifaldyazkaa/koyorin#123]
Documentation page link that aims to https://gifaldyazka.is-a.dev/koyorin response 404 status code.
Did you forget to change it to https://falcxxdev.ml/koyorin/ ?

**Comment by gifaldyazkaa** [comment]
Oh, i'm forgetting this one. Thanks for reminding me bout' this. gonna fix this right now!

**Comment by gifaldyazkaa** [comment]
✅ Resolved at commit [`08f38ce`](https://github.com/gifaldyazkaa/koyorin/commit/08f38ce4a020d279b66dae1262eeaf8ecf9736c5)
